### ISSUE TITLE
Advertise soju.im/SAFERATE when connect:fakelag is enabled

### ISSUE THREAD

**Issue by delthas** [inspircd/inspircd#2150]
### Description

[soju.im/SAFERATE](https://codeberg.org/emersion/soju/src/branch/master/doc/ext/saferate.md) enables servers to advertise that they do buffering/fakelag on their side for incoming messages, letting clients send messages without prior throttling.

When connect:fakelag is enabled, InspIRCd could advertise that ISUPPORT token so that clients and bouncers know that they do not need to do conservative buffering.

### Why this would be useful?

This would enable clients to be more reactive when sending multiple messages in succession, rather than relying on their client conversative rate limiting.

**Comment by ptaylor2** [comment]
I am against and the IRC Networks are already having issues with IP spoofing, flooding, advertising the other little kiddie stuff that the users do now.

**Comment by SadieCat** [comment]
> I am against and the IRC Networks are already having issues with IP spoofing, flooding, advertising the other little kiddie stuff that the users do now.

Advertising this token doesn't change anything regarding flood limiting its already reasonably easy for botters to detect whether fakelag is enabled.

**Comment by SadieCat** [comment]
Is there any reason this is vendor prefixed btw? I don't think most implementations bother doing that for 005 tokens.

**Comment by emersion** [comment]
Same reason why caps are prefixed: if someone else entirely happens to add a token with the same name, they don't end up with conflicts. If the token ends up getting standardized but with different semantics (e.g. requirements for clients), it's clear which spec servers support.

ISUPPORT tokens gated behind a cap are less of an issue since the vendor-prefixed cap already indicates which flavor of the spec is supported.

**Comment by SadieCat** [comment]
Historically this isn't how ISUPPORT tokens have worked and every vendor has added their own tokens and to my knowledge there hasn't been any conflicts. There's a registry on ircdocs if necessary.

**Comment by SadieCat** [comment]
I implemented something more or less the same as this in 5ea0bfff6fdb21d668263d1e54f9078fdecc8cd6.

**Comment by delthas** [comment]
Um, it'd be nice if we could agree on the same token 😛 Perhaps as a middle ground we could use unprefixed `SAFERATE`? `FAKELAG` does sound a bit implementation-dependent (ergo would also support the token but does not do fakelag per se). 

As it is I'm not sure it would make sense for soju / @emersion to add a custom heuristic for `FAKELAG` in addition to `SAFERATE`.

**Comment by SadieCat** [comment]
I'm fine with any name as long as its not vendor prefixed. I'm happy to change it to SAFERATE if that is accepted by other implementations.

**Comment by Robby-** [comment]
Wait, simply renaming from `FAKELAG` to `SAFERATE` isn't enough in the case of inspircd I think, right? Because clients will still get disconnected for `RecvQ exceeded` when flooding the server. Having read this `SAFERATE` spec linked in the opening post which actually seeks to *not* disconnect flooding clients, I'd guess adding a new config option that disables the disconnecting would be required, and only then `SAFERATE` should be advertised.

**Comment by SadieCat** [comment]
> Wait, simply renaming from `FAKELAG` to `SAFERATE` isn't enough in the case of inspircd I think, right? Because clients will still get disconnected for `RecvQ exceeded` when flooding the server.

Eventually yes butbthe fakelag hard limit is generally high enough that clients shouldn't need to limit sending messages.

**Comment by Robby-** [comment]
We have been using `<connect:fakelag="yes">` in combination with a smaller-than-default `<connect:recvq>` for well over a decade to frustrate manual intentional or accidental flooding by people using IRC clients, and to more easily detect that some suspicious activity is going on (either by bots or by people) because we see the `RecvQ exceeded` disconnections in the channels as well as via server notices. We would very much like to be able to keep using it in this way.
